---
title: "DA test report"
author: "Mingkai Jiang"
date: "March 8, 2018"
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


1. Description
--------------
Here I am testing the Ensemble Kalman Filter (EnKF) function with fake data. The idea is that, neither models nor observations can perfectly describe a system, but an analysis that combines model and data will provide a better estimate of system dynamics than model or obserations alone (Williams et al., 2005). 

The basic KF requires three assumptions:

    1. a mineal model can describe the system;
    2. the system noise is white and Gaussian;
    3. the measurement noise is white and Gaussian.
    
The product of KF is an estimate, or analysis, of the state variables that takes account of prior knowledge plus new observations to ensure that estimated errors are statistically minimized. 

The KF generates a variance-minimizing analysis by combining the model forecast with the observations, weighted according to these prediction and measurement error covariances. If measurement noise is large, rleatively less emphasis is placed on the current observation. If meausrement noise is small, or the model estimation error is large, the corrected estimate appraoches the observation. 

As inputs, the KF requires details on the covariances of both the model forecast and of the measurements. The error covariance of the measurements can be derived from knowledge of the accuracy of the techniques used to measure them. The error covariances for the model prediction are computed by solving an equation for the evolution in time of the error covariance matrix of the model state. 

The KF uses covariance matrices to store information on the uncertainty in the models, observations, and analysis. Storing, integrating and inverting large covariance matrices is computationally expensive and the matrix operations required for the analysis are not always robust. Evensen (1994) suggested that, instead of storing a full covariance matrix, the same error statistics can be represented approximately using an appropriate ensemble of model states. The EnKF uses a Markov Chain Monte Carlo method to solve the time evolution of the probability density of the model state. The probability density is represented by a large ensemble of model states, and these are integrated forward in time by a differential equation (i.e. the model) with a stochastic forcing term representing the model errors. 

Correct estimation of observational error is crucial to the quality of the analysis, because the magnitude of observational errors determines to what extent the simulated fields will be corrected to match the observations. Observation error variances are best specified by knowledge of instrumental characteristics, and by comparing replicated samples. Observation error correlations are usually assumed to be zero - distinct measurements are assumed to be affected by physically independent errors. In most cases, we specify the standard deviation of model error as a percentage of the mean. 


